const PDFDocument = require('pdfkit');

module.exports = async (req, res) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { artistName, songTitle, genre, releaseDate, budget, strategy } = req.body;

  if (!strategy) {
    return res.status(400).json({ error: 'No strategy provided' });
  }

  try {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => {
      const pdf = Buffer.concat(chunks);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="Inqo_Strategy_${artistName}.pdf"`);
      res.send(pdf);
    });

    // Header background
    doc.rect(0, 0, 595, 80).fill('#0F0F0F');

    // inqo. logo
    doc.fontSize(24).fillColor('#F97316').font('Helvetica-Bold').text('inqo.', 50, 20);
    doc.fontSize(11).fillColor('#AAAAAA').font('Helvetica').text('Music Promotion Strategy Report', 50, 50);

    // Orange accent line
    doc.rect(0, 80, 595, 4).fill('#F97316');

    // Artist info card
    doc.rect(50, 100, 495, 110).fill('#F9F9F7');
    doc.rect(50, 100, 4, 110).fill('#F97316');

    doc.fontSize(11).fillColor('#1A1A1A');
    doc.font('Helvetica-Bold').text('Artist:', 65, 115).font('Helvetica').text(artistName || 'N/A', 120, 115);
    doc.font('Helvetica-Bold').text('Song:', 65, 135).font('Helvetica').text(songTitle || 'N/A', 120, 135);
    doc.font('Helvetica-Bold').text('Genre:', 65, 155).font('Helvetica').text(genre || 'N/A', 120, 155);
    doc.font('Helvetica-Bold').text('Release Date:', 65, 175).font('Helvetica').text(releaseDate || 'N/A', 165, 175);
    doc.font('Helvetica-Bold').text('Budget:', 65, 195).font('Helvetica').text(budget || 'N/A', 120, 195);

    // Strategy content
    doc.moveDown(3);
    const cleanText = strategy
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/### (.*?)(\n|$)/g, '\n$1\n')
      .replace(/## (.*?)(\n|$)/g, '\n$1\n')
      .replace(/# (.*?)(\n|$)/g, '\n$1\n');

    const lines = cleanText.split('\n');
    let yPosition = 230;

    for (const line of lines) {
      if (yPosition > 760) {
        doc.addPage();
        yPosition = 50;
      }

      const trimmed = line.trim();
      if (!trimmed) {
        yPosition += 8;
        continue;
      }

      if (trimmed.match(/^\d+\.|^#{1,3}\s/)) {
        doc.fontSize(12).fillColor('#F97316').font('Helvetica-Bold');
        doc.text(trimmed.replace(/^#{1,3}\s/, '').replace(/^\d+\.\s/, ''), 50, yPosition, { width: 495 });
        yPosition += 22;
      } else if (trimmed.startsWith('**') || trimmed.startsWith('*')) {
        doc.fontSize(10).fillColor('#1A1A1A').font('Helvetica-Bold');
        doc.text(trimmed.replace(/\*+/g, ''), 50, yPosition, { width: 495 });
        yPosition += 16;
      } else {
        doc.fontSize(10).fillColor('#333333').font('Helvetica');
        doc.text(trimmed, 50, yPosition, { width: 495 });
        yPosition += 14;
      }
    }

    // Footer
    if (yPosition > 760) { doc.addPage(); yPosition = 750; }
    doc.rect(0, 820, 595, 30).fill('#0F0F0F');
    doc.fontSize(9).fillColor('#999999').font('Helvetica')
      .text('Generated by Inqo AI · Confidential — For Artist Use Only', 50, 807, { align: 'center', width: 495 });

    doc.end();

  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};
