const PDFDocument = require('pdfkit');

module.exports = async (req, res) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { artistName, songTitle, genre, releaseDate, budget, strategy } = req.body;

  if (!strategy) {
    return res.status(400).json({ error: 'No strategy provided' });
  }

  const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
  const chunks = [];

  doc.on('data', chunk => chunks.push(chunk));
  doc.on('end', () => {
    const pdf = Buffer.concat(chunks);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="Inqo_Strategy.pdf"`);
    res.end(pdf);
  });

  // Header
  doc.rect(0, 0, 595, 75).fill('#0F0F0F');
  doc.fontSize(22).fillColor('#F97316').font('Helvetica-Bold').text('inqo.', 50, 18);
  doc.fontSize(10).fillColor('#AAAAAA').font('Helvetica').text('Music Promotion Strategy Report', 50, 48);
  doc.rect(0, 75, 595, 3).fill('#F97316');

  // Info box
  doc.rect(50, 95, 495, 95).fill('#F9F9F7');
  doc.rect(50, 95, 3, 95).fill('#F97316');
  doc.fontSize(10).fillColor('#1A1A1A');
  doc.font('Helvetica-Bold').text('Artist: ', 62, 108, {continued: true}).font('Helvetica').text(artistName || '');
  doc.font('Helvetica-Bold').text('Song: ', 62, 124, {continued: true}).font('Helvetica').text(songTitle || '');
  doc.font('Helvetica-Bold').text('Genre: ', 62, 140, {continued: true}).font('Helvetica').text(genre || '');
  doc.font('Helvetica-Bold').text('Release: ', 62, 156, {continued: true}).font('Helvetica').text(releaseDate || '');
  doc.font('Helvetica-Bold').text('Budget: ', 62, 172, {continued: true}).font('Helvetica').text(budget || '');

  // Strategy text - clean and dump directly
  const clean = strategy
    .replace(/\*\*/g, '')
    .replace(/#{1,3} /g, '')
    .substring(0, 8000); // limit length for speed

  doc.moveDown(2);
  doc.fontSize(10).fillColor('#1A1A1A').font('Helvetica').text(clean, 50, 210, {
    width: 495,
    lineGap: 4
  });

  // Footer
  doc.fontSize(9).fillColor('#999999').text(
    'Generated by Inqo AI · Confidential — For Artist Use Only',
    50, doc.page.height - 40, { align: 'center', width: 495 }
  );

  doc.end();
};
